### ISSUE TITLE
How to had the widgets_and_configuration.yaml? no writable entities in HA

### ISSUE THREAD

**Issue by Patbonamy** [ysard/ebusd_configuration_chaffoteaux_bridgenet#6]
Hi Ysard,
Thanks for your work,
I use the ebusd add-on  in HA with a wifi adapter 
I can have all the reading sensors with the mqtt-hassio.cfg patched.
But I have no writable entities to pilot my Mira C green
I try to had the widgets_and_configuration.yaml, I try to rename it to customize.yaml and hading customize: !include customize.yaml under homeassistant: I have these errors: nvalid config for 'homeassistant' at customize.yaml, line 129: 'counter' is an invalid option for 'homeassistant', check: customize->counter
Invalid config for 'homeassistant' at customize.yaml, line 134: 'sensor' is an invalid option for 'homeassistant', check: customize->sensor
Invalid config for 'homeassistant' at customize.yaml, line 142: 'automation format_error_code' is an invalid option for 'homeassistant', check: customize->automation format_error_code
Invalid config for 'homeassistant' at customize.yaml, line 19: 'input_select' is an invalid option for 'homeassistant', check: customize->input_select
Invalid config for 'homeassistant' at customize.yaml, line 286: 'homeassistant' is an invalid option for 'homeassistant', check: customize->homeassistant
Invalid config for 'homeassistant' at customize.yaml, line 39: 'automation z1_thermoreg_type' is an invalid option for 'homeassistant', check: customize->automation z1_thermoreg_type
Invalid config for 'homeassistant' at customize.yaml, line 85: 'automation dhw_comfort_mode' is an invalid option for 'homeassistant', check: customize->automation dhw_comfort_mode 
when I check my config

Can you help ?
Thanks

**Comment by Patbonamy** [comment]
> Hi Ysard, Thanks for your work, I use the ebusd add-on in HA with a wifi adapter I can have all the reading sensors with the mqtt-hassio.cfg patched. But I have no writable entities to pilot my Mira C green I try to had the widgets_and_configuration.yaml, I try to rename it to customize.yaml and hading customize: !include customize.yaml under homeassistant: I have these errors: nvalid config for 'homeassistant' at customize.yaml, line 129: 'counter' is an invalid option for 'homeassistant', check: customize->counter Invalid config for 'homeassistant' at customize.yaml, line 134: 'sensor' is an invalid option for 'homeassistant', check: customize->sensor Invalid config for 'homeassistant' at customize.yaml, line 142: 'automation format_error_code' is an invalid option for 'homeassistant', check: customize->automation format_error_code Invalid config for 'homeassistant' at customize.yaml, line 19: 'input_select' is an invalid option for 'homeassistant', check: customize->input_select Invalid config for 'homeassistant' at customize.yaml, line 286: 'homeassistant' is an invalid option for 'homeassistant', check: customize->homeassistant Invalid config for 'homeassistant' at customize.yaml, line 39: 'automation z1_thermoreg_type' is an invalid option for 'homeassistant', check: customize->automation z1_thermoreg_type Invalid config for 'homeassistant' at customize.yaml, line 85: 'automation dhw_comfort_mode' is an invalid option for 'homeassistant', check: customize->automation dhw_comfort_mode when I check my config
> 
> Can you help ? Thanks

For the writables entities it's seem to be a bug from the HA add-on the path for the mqqt-hassion.cfg won't work it's only load the default path so I put my file in the default path and I have my writables entities .

**Comment by ysard** [comment]
Hi, Ok for the correction of the writable entities.

For the rest, you should copy/paste the contents of the `widgets_and_automations.yaml` file into your `.homeassistant/configuration.yaml` file.
Unless you want to strictly separate each type of entity/automation into independent files, I think this is the easiest way to start.

You should have something like this:
```
...
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

python_script:

<insert file content here>
```

**Comment by Patbonamy** [comment]
Thanks Ysard,
I have tried your configuration but it doesn't work.
It has broken some sensor of my boiler, so I have to uninstall and reinstall the addon.
Now all is working.
Regards

**Comment by ysard** [comment]
Hi, could you be more explicit about what's not working? it might help other people. In the end, this project doesn't work on your boiler which is a Mira C Green like mine ?

**Comment by Patbonamy** [comment]
> Hi, could you be more explicit about what's not working? it might help other people. In the end, this project doesn't work on your boiler which is a Mira C Green like mine ?

Hi Izard, 
For me it's working, the same boiler as you, I make a mistake there is no bug on the add-on the path of the config file, it was not save in the configuration of the add-on. I need to save it twice and after it's working.
I use the connexion in enh on port 3335 of my EBUS to WiFi adapter: https://www.lectronz.com/products/ebus-to-wifi-adapter-module
So now I can control my Boiler Mira C Green. I don't use the widgets_and_automations.yaml
I just need some adjustement before the winter...
If people needs I can share my csv files, sames like you, and my mqtt-hassio.cfg.

Thanks for your work.
Regards
